name: drug-screening
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytest
  - jupyter
  - pandas
  - openpyxl
  - plotly
  - seaborn
  - scikit-learn
  - PyYAML==6.0
  - jenkspy
  - numpy
  - rdkit
  - pyarrow
  - dash
  - umap-learn
